### ISSUE TITLE
QUESTION: Can text be spoken out when app is in background or device in sleep (for possible silent notification use)?

### ISSUE THREAD

**Issue by wumke** [cinder92/react-native-speach-text#2]
Just a question:
 Can text be spoken out when app is in background or device in sleep (for possible silent notification use)?

**Comment by cinder92** [comment]
On this this can be done by adding in your AppDelegate.m

the following code

```
// MARK: - Keep Audio in Background
  AVAudioSession *audioSession = [AVAudioSession sharedInstance];
  BOOL ok;
  NSError *setCategoryError = nil;
  ok = [audioSession setCategory:AVAudioSessionCategoryPlayback error:&setCategoryError];
```

on Android, we need to make some changes...

**Comment by wumke** [comment]
This would be great info to share in the readme!

If, in some parallel universe, I find the time to implement an idea of mine I will give this package a go.
When combining voice control with this speaking package you can create nice apps that work without touching your phone!

**Comment by cinder92** [comment]
@wumke its a good idea! sadly im not a good developer at android, but if i have time, i will try.

Then for iOS that code works for you?

**Comment by wumke** [comment]
I did not try it yet, but I've seen mp3 players and even webrtc voice calls that continue when the device turns the screen off... The iOS code makes sense to me, I remember using that trick to solve something in the past now i see the code. In general iOS is much more limiting than Android for this kind of things. If I find the time to experiment I will post useful related info here.
